export const CONFIG = {
  destinations: {
    facebook: "https://www.facebook.com/MitosEnterrados",
    blog: "https://mitosenterrados.blogspot.com/",
  },

  ganchos: [
    "la-leyenda-de",
    "la-leyenda-prohibida-de",
    "el-secreto-oscuro-de",
    "el-misterio-sin-resolver-de",
    "testimonios-aterradores-de",
    "la-verdad-oculta-sobre",
    "el-ritual-olvidado-de",
    "evidencias-perturbadoras-de",
    "la-historia-que-nadie-cuenta-de",
    "el-caso-cerrado-de",
    "fotos-reales-de",
  ],

  sujetos: [
    "fantasmas",
    "aliens",
    "ovnis",
    "illuminati",
    "entidades-oscuras",
    "criptidos",
    "demonios",
    "espiritus-errantes",
    "sociedades-secretas",
    "viajeros-del-tiempo",
    "maldiciones-antiguas",
    "seres-de-luz",
    "poltergeist",
    "leyendas-urbanas",
  ],

  ubicaciones: [
    "mexico",
    "espana",
    "argentina",
    "colombia",
    "peru",
    "chile",
    "estados-unidos",
    "madrid",
    "buenos-aires",
    "cdmx",
    "bogota",
    "lima",
    "santiago",
    "hospitales-abandonados",
    "cementerios-antiguos",
    "bosques-oscuros",
    "cuevas-secretas",
    "casas-embrujadas",
    "vaticano",
    "area-51",
    "piramides-de-egipto",
    "amazonas",
  ],

  intenciones: [
    "fotos-reales",
    "evidencia-grabada",
    "la-verdad-completa",
    "documental-prohibido",
    "testimonios-reales",
    "explicacion-cientifica",
    "teorias-conspirativas",
    "pruebas-irrefutables",
    "relatos-de-sobrevivientes",
    "videos-filtrados",
  ],
};
